
const data = [ 

    {
        Foryear: "2020-21",
        roll: "21102A0023",
        fname: "Prathamesh Swar",
        email: "Prathamesh Swar@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "B",
        Batch: 2024,
        year:"TE",
        Company: "YHills",
        Domain: "Software Developer"
       },
       {
        Foryear: "2020-21",
        roll: "21102A0024",
        fname: "Aaditya Shewale",
        email: "Aaditya Shewale@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "B",
        Batch: 2025,
        year:"SE",
        Company: "LetsGrowMore",
        Domain: "Web development"
       },
       {
        Foryear: "2020-21",
        roll: "21102A0025",
        fname: "Vanashree Pinjari",
        email: "Vanashree Pinjari@\"vit.edu.in",
        phone: 123456789,
        Sem: 4,
        div: "A",
        Batch: 2025,
        year:"SE",
        Company: "The Sparks Foundation",
        Domain: "Web development"
       },
       {
        Foryear: "2020-21",
        roll: "21102A0026",
        fname: "Ashutosh Gupta",
        email: "Ashutosh Gupta@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "A",
        Batch: 2024,
        year:"TE",
        Company: "LetsGrowMore",
        Domain: "Web development "
       },
       {
        Foryear: "2020-21",
        roll: "21102A0027",
        fname: "Rajashree Shingne",
        email: "Rajashree Shingne@\"vit.edu.in",
        phone: 123456789,
        Sem: 3,
        div: "B",
        Batch: 2025,
        year:"SE",
        Company: "Antenna",
        Domain: "Web Development "
       },
       {
        Foryear: "2020-21",
        roll: "21102A0028",
        fname: "Kartik Gokhale",
        email: "Kartik Gokhale@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "A",
        Batch: 2024,
        year:"TE",
        Company: "Cyber Secured India",
        Domain: "Full Stack Development"
       },
       {
        Foryear: "2020-21",
        roll: "21102A0031",
        fname: "Bhavesh Limbare",
        email: "Bhavesh Limbare@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "A",
        Batch: 2023,
        year:"BE",
        Company: "Bolt",
        Domain: "Content Writing"
       },
       {
        Foryear: "2020-21",
        roll: "21102A0034",
        fname: "Aarushi Bose",
        email: "Aarushi Bose@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "A",
        Batch: 2025,
        year:"SE",
        Company: "The Sparks foundation",
        Domain: "Cyber Security "
       },
       {
        Foryear: "2020-21",
        roll: "21102A0036",
        fname: "Rohit Bhandwalkar",
        email: "Rohit Bhandwalkar@\"vit.edu.in",
        phone: 123456789,
        Sem: 5,
        div: "B",
        Batch: 2023,
        year:"BE",
        Company: "Letsgrowmore",
        Domain: "Front end developer "
       },
       {
        Foryear: "2020-21",
        roll: "21102A0037",
        fname: "Sukant Thombare",
        email: "Sukant Thombare@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "B",
        Batch: 2024,
        year:"TE",
        Company: "LetsGrowMore",
        Domain: "Web development "
       },
       {
        Foryear: "2020-21",
        roll: "21102A0039",
        fname: "Noel Lawrence",
        email: "Noel Lawrence@\"vit.edu.in",
        phone: 123456789,
        Sem: 4,
        div: "A",
        Batch: 2023,
        year:"BE",
        Company: "The Sparks Foundation",
        Domain: "Web development "
       },
    {
     Foryear: "2022-23",
     roll: "21102A0040",
     fname: "Harshali Bhoye",
     email: "Harshali Bhoye@\"vit.edu.in",
     phone: 123456789,
     Sem: 6,
     div: "B",
     Batch: 2024,
     year:"TE",
     Company: "The Sparks Foundation",
     Domain: "Data Science and Machine Learning "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0041",
     fname: "Shreya Ingle",
     email: "Shreya Ingle@\"vit.edu.in",
     phone: 123456789,
     Sem: 5,
     div: "B",
     Batch: 2023,
     year:"BE",
     Company: "The Sparks foundation",
     Domain: "Web development "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0043",
     fname: "Shantanu Lagvankar",
     email: "Shantanu Lagvankar@\"vit.edu.in",
     phone: 123456789,
     Sem: 3,
     div: "B",
     Batch: 2024,
     year:"TE",
     Company: "The Sparks Foundation",
     Domain: "Web Development "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0044",
     fname: "Chaitanya  Mandale",
     email: "Chaitanya  Mandale@\"vit.edu.in",
     phone: 123456789,
     Sem: 6,
     div: "B",
     Batch: 2024,
     year:"TE",
     Company: "The Sparks foundation",
     Domain: "Data science "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0045",
     fname: "Mukund Iyer",
     email: "Mukund Iyer@\"vit.edu.in",
     phone: 123456789,
     Sem: 6,
     div: "B",
     Batch: 2023,
     year:"BE",
     Company: "Letsgrowmore",
     Domain: "Data science and Business analytics "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0046",
     fname: "Sanket Bole",
     email: "Sanket Bole@\"vit.edu.in",
     phone: 123456789,
     Sem: 5,
     div: "A",
     Batch: 2025,
     year:"SE",
     Company: "Cyber Secured India",
     Domain: "Data science "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0047",
     fname: "Ayush Mohite",
     email: "Ayush Mohite@\"vit.edu.in",
     phone: 123456789,
     Sem: 7,
     div: "B",
     Batch: 2024,
     year:"TE",
     Company: "YHills",
     Domain: "Web development "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0048",
     fname: "Harsh Ahire",
     email: "Harsh Ahire@\"vit.edu.in",
     phone: 123456789,
     Sem: 8,
     div: "A",
     Batch: 2023,
     year:"BE",
     Company: "LetsGrowMore",
     Domain: "Cybersecurity and Digital Forensics"
    },
    {
     Foryear: "2022-23",
     roll: "21102A0049",
     fname: "Darshan Mahajan",
     email: "Darshan Mahajan@\"vit.edu.in",
     phone: 123456789,
     Sem: 4,
     div: "B",
     Batch: 2025,
     year:"SE",
     Company: "The Sparks Foundation",
     Domain: "Data Science "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0050",
     fname: "Aakanksha Bhagure",
     email: "Aakanksha Bhagure@\"vit.edu.in",
     phone: 123456789,
     Sem: 5,
     div: "A",
     Batch: 2024,
     year:"TE",
     Company: "LetsGrowMore",
     Domain: "Web Development "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0052",
     fname: "Ayush Makade",
     email: "Ayush Makade@\"vit.edu.in",
     phone: 123456789,
     Sem: 5,
     div: "A",
     Batch: 2023,
     year:"BE",
     Company: "Antenna",
     Domain: "Data science "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0053",
     fname: "Mayank Fulzele",
     email: "Mayank Fulzele@\"vit.edu.in",
     phone: 123456789,
     Sem: 7,
     div: "B",
     Batch: 2024,
     year:"TE",
     Company: "LetsGrowMore",
     Domain: "Web development "
    },
    {
     Foryear: "2022-23",
     roll: "21102A0054",
     fname: "Aryan Kshatriya",
     email: "Aryan Kshatriya@\"vit.edu.in",
     phone: 123456789,
     Sem: 4,
     div: "A",
     Batch: 2023,
     year:"BE",
     Company: "The Sparks Foundation",
     Domain: "Software Developer"
    },
    {
     Foryear: "2022-23",
     roll: "21102A0055",
     fname: "Satish Udaiyar",
     email: "Satish Udaiyar@\"vit.edu.in",
     phone: 123456789,
     Sem: 4,
     div: "A",
     Batch: 2025,
     year:"SE",
     Company: "LetsGrowMore",
     Domain: "Software Developer"
    },
    {
        Foryear: "2021-22",
        roll: "21102A0001",
        fname: "Digvijay Mawale",
        email: "Digvijay Mawale@\"vit.edu.in",
        phone: 123456789,
        Sem: 2,
        div: "B",
        Batch: 2024,
        year:"TE",
        Company: "The Sparks Foundation",
        Domain: "Web development"
       },
       {
        Foryear: "2021-22",
        roll: "21102A0002",
        fname: "Rutuja Gujare",
        email: "Rutuja Gujare@\"vit.edu.in",
        phone: 123456789,
        Sem: 4,
        div: "A",
        Batch: 2024,
        year:"TE",
        Company: "Kids Galaxy",
        Domain: "Web development"
       },
       {
        Foryear: "2021-22",
        roll: "21102A0003",
        fname: "Omkar Patil",
        email: "Omkar Patil@\"vit.edu.in",
        phone: 123456789,
        Sem: 5,
        div: "B",
        Batch: 2023,
        year:"BE",
        Company: "The Sparks Foundation",
        Domain: "Web development "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0004",
        fname: "Diksha Vodnala",
        email: "Diksha Vodnala@\"vit.edu.in",
        phone: 123456789,
        Sem: 3,
        div: "A",
        Batch: 2025,
        year:"SE",
        Company: "Human Tales Technology Pvt Ltd",
        Domain: "Web Development "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0005",
        fname: "Pranav Redij",
        email: "Pranav Redij@\"vit.edu.in",
        phone: 123456789,
        Sem: 7,
        div: "A",
        Batch: 2023,
        year:"BE",
        Company: "The Sparks foundation",
        Domain: "Full Stack Development"
       },
       {
        Foryear: "2021-22",
        roll: "21102A0006",
        fname: "Sahil Pokharkar",
        email: "Sahil Pokharkar@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "B",
        Batch: 2025,
        year:"SE",
        Company: "LetsGrowMore",
        Domain: "Content Writing"
       },
       {
        Foryear: "2021-22",
        roll: "21102A0007",
        fname: "Sayali Tawade",
        email: "Sayali Tawade@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "B",
        Batch: 2025,
        year:"SE",
        Company: "LetsGrowMore",
        Domain: "Cyber Security "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0008",
        fname: "Aayush Srivastava",
        email: "Aayush Srivastava@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "A",
        Batch: 2025,
        year:"SE",
        Company: "LetsGrowMore",
        Domain: "Front end developer "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0009",
        fname: "Nikhil Dhumal",
        email: "Nikhil Dhumal@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "A",
        Batch: 2025,
        year:"SE",
        Company: "Mobinext Technologies Pvt. Limited",
        Domain: "Web development "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0010",
        fname: "Anvi Borse",
        email: "Anvi Borse@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "A",
        Batch: 2023,
        year:"BE",
        Company: "Kids Galaxy",
        Domain: "Web development "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0011",
        fname: "Swaraj Andhale",
        email: "Swaraj Andhale@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "B",
        Batch: 2023,
        year:"BE",
        Company: "Cyber Secured India",
        Domain: "Data Science and Machine Learning "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0012",
        fname: "Vedant Rane",
        email: "Vedant Rane@\"vit.edu.in",
        phone: 123456789,
        Sem: 5,
        div: "B",
        Batch: 2025,
        year:"SE",
        Company: "Bolt",
        Domain: "Web development "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0013",
        fname: "Shreekant Pukale",
        email: "Shreekant Pukale@\"vit.edu.in",
        phone: 123456789,
        Sem: 7,
        div: "B",
        Batch: 2025,
        year:"SE",
        Company: "The Sparks foundation",
        Domain: "Web Development "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0014",
        fname: "Deep Salunkhe",
        email: "Deep Salunkhe@\"vit.edu.in",
        phone: 123456789,
        Sem: 3,
        div: "B",
        Batch: 2024,
        year:"TE",
        Company: "Letsgrowmore",
        Domain: "Data science "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0015",
        fname: "Gauri Naik",
        email: "Gauri Naik@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "A",
        Batch: 2023,
        year:"BE",
        Company: "LetsGrowMore",
        Domain: "Data science and Business analytics "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0016",
        fname: "Premanshu Chaudhari",
        email: "Premanshu Chaudhari@\"vit.edu.in",
        phone: 123456789,
        Sem: 6,
        div: "A",
        Batch: 2025,
        year:"SE",
        Company: "The Sparks Foundation",
        Domain: "Data science "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0017",
        fname: "Mayur Hile",
        email: "Mayur Hile@\"vit.edu.in",
        phone: 123456789,
        Sem: 7,
        div: "A",
        Batch: 2023,
        year:"BE",
        Company: "The Sparks Foundation",
        Domain: "Web development "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0018",
        fname: "Ritesh Tiwari",
        email: "Ritesh Tiwari@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "B",
        Batch: 2023,
        year:"BE",
        Company: "The Sparks foundation",
        Domain: "Cybersecurity and Digital Forensics"
       },
       {
        Foryear: "2021-22",
        roll: "21102A0019",
        fname: "Akash  Mendke",
        email: "Akash  Mendke@\"vit.edu.in",
        phone: 123456789,
        Sem: 8,
        div: "B",
        Batch: 2024,
        year:"TE",
        Company: "The Sparks Foundation",
        Domain: "Data Science "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0020",
        fname: "Prachet Pandav",
        email: "Prachet Pandav@\"vit.edu.in",
        phone: 123456789,
        Sem: 3,
        div: "B",
        Batch: 2025,
        year:"SE",
        Company: "The Sparks foundation",
        Domain: "Web Development "
       },
       {
        Foryear: "2021-22",    
        roll: "21102A0021",
        fname: "Soham Pashte",
        email: "Soham Pashte@\"vit.edu.in",
        phone: 123456789,
        Sem: 3,
        div: "B",
        Batch: 2024,
        year:"TE",
        Company: "Letsgrowmore",
        Domain: "Data science "
       },
       {
        Foryear: "2021-22",
        roll: "21102A0022",
        fname: "Prathamesh  Palatshaha",
        email: "Prathamesh  Palatshaha@\"vit.edu.in",
        phone: 123456789,
        Sem: 4,
        div: "A",
        Batch: 2024,
        year:"TE",
        Company: "Cyber Secured India",
        Domain: "Web development "
       },
   ]
   export default data;